<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AiSdk.UiStreamProtocol\AiSdk.UiStreamProtocol.csproj" />
    <ProjectReference Include="..\AiSdk.UiStreamProtocol.AspNetCore\AiSdk.UiStreamProtocol.AspNetCore.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
